<?php
/**
 * Implementation of hook_menu().
 */
function localsite_custom_menu() {
  $items['venue-maps-floorplans'] = array(
		'title' => 'Maps & Floorplans',
		'page callback' => 'maps_floorplans',
		'access callback' => TRUE,
  );
	$items['registration-fee'] = array(
		'title' => 'Registration Fee',
		'page callback' => 'registration_fee',
		'access callback' => TRUE,
  );
	$items['contact-us'] = array(
		'title' => 'Contact Us',
		'page callback' => 'contact_us',
		'access callback' => TRUE,
  );
	return $items;
}

function maps_floorplans(){
	return "";
}

function registration_fee(){
	return "";
}

function contact_us(){
	return "";
}